### ISSUE TITLE
Hi, I can't run your DMP code, what is your matlab version?

### ISSUE THREAD

**Issue by Dreamer-DLUT** [mosesnah-shared/DMP-MATLAB#1]
Hi, I can't run your DMP code, what is your matlab version?

**Comment by MosesAndLily** [comment]
Hello Dreamer-DLUT.

Thank you for your interest. Currently, I'm using the most recent MATLAB version, 2023-a. but I checked that it worked for MATLAB versions after 2021.

On the directory of DMP-MATLAB repository, run the `setup.m` file. You can run the script on the MATLAB command window. Then you will be all set. Let me know if this doesn't resolve your issue.

I'll add some details about this on the `README.md` file.

**Comment by Dreamer-DLUT** [comment]
> Hello Dreamer-DLUT.
> 
> Thank you for your interest. Currently, I'm using the most recent MATLAB version, 2023-a. but I checked that it worked for MATLAB versions after 2021.
> 
> On the directory of DMP-MATLAB repository, run the `setup.m` file. You can run the script on the MATLAB command window. Then you will be all set. Let me know if this doesn't resolve your issue.
> 
> I'll add some details about this on the `README.md` file.

Dear Dr. Moses.

     Haha, Thanks for your answer, it is very helpful to me. I have successfully run the DMP-MATLAB code.

     Thank you again!
